/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.archivos;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author erics
 */
public class Archivos extends javax.swing.JFrame {
    DefaultListModel carpetas;
    DefaultListModel archiv;
    DefaultListModel ocultos;
    
    
    
    /**
     * Creates new form Archivos
     */
    public Archivos() {
        initComponents();
        this.setTitle("Busqueda de Archivos");
        
        setIconImage(new ImageIcon(("src/ec/edu/ups/archivos/iconoooo.png")).getImage());
        setLocationRelativeTo(null);

        carpetas = new DefaultListModel<>();
        listacarpetas.setModel(carpetas);

        archiv = new DefaultListModel<>();
        listaarchivos.setModel(archiv);

        ocultos = new DefaultListModel<>();
        listaocultos.setModel(ocultos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txturl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listacarpetas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaarchivos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaocultos = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel3.setText("Fecha de Modificacion:");

        jLabel4.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel4.setText("Ruta Absoluta:");

        jLabel5.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel5.setText("Tamaño:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        jLabel1.setText("Busqueda de Archivos");

        jLabel2.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel2.setText("Direccion URL:");

        txturl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txturlActionPerformed(evt);
            }
        });

        listacarpetas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listacarpetasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listacarpetas);

        listaarchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaarchivosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaarchivos);

        listaocultos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaocultosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaocultos);

        jMenu1.setText("Archivos");

        jMenuItem1.setText("CrearArchivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txturl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(132, 132, 132)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txturl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        vaciarTabla();
        File direccion;
        //.trim elimina espacios tanto de derecha como izquierda
        direccion = new File(txturl.getText().trim());
        File[] archivos = direccion.listFiles();

        for (File archivo : archivos) {
            if (archivo.isDirectory()) {
                if (archivo.isHidden()) {
                    //Ocultos
                    String lista = archivo.getName();
                    ocultos.addElement(lista);
                } else {
                    //Carpetas
                    String lista = archivo.getName();
                    carpetas.addElement(lista);
                }

            } else if (archivo.isFile()) {

                if (archivo.isHidden()) {
                    //Oculto
                    String lista = archivo.getName();
                    ocultos.addElement(lista);
                } else {
                    //Archivos
                    String lista = archivo.getName();
                    archiv.addElement(lista);
                }

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed
     public void vaciarTabla() {
        
        DefaultListModel listModel = (DefaultListModel)  listacarpetas.getModel();
        listModel.removeAllElements();
        DefaultListModel listModel2 = (DefaultListModel) listaarchivos.getModel();
        listModel2.removeAllElements();
        DefaultListModel listModel3 = (DefaultListModel) listaocultos.getModel();
        listModel3.removeAllElements();
    }
    
    
    
    
    
    
    
    private void txturlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txturlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txturlActionPerformed

    private void listacarpetasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listacarpetasValueChanged
        // TODO add your handling code here:
        String elementoseleccionado = (String) listacarpetas.getSelectedValue();
        // System.out.println("Elemento: "+ elementoseleccionado);
        String rutasele = txturl.getText().trim() + "\\" + elementoseleccionado;
        //System.out.println("Ruta elemento Seleccionado: "+ rutasele);
        //Conseguir la fecha de ultima actualizacion
        File archivoSelecc = new File(rutasele);
        long modificacion = archivoSelecc.lastModified();
        Date modiDate = new Date(modificacion);
        SimpleDateFormat fechamodificacion = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = fechamodificacion.format(modiDate);
        jLabel3.setText("Fecha modificacion: " + fecha);

        //Ruta Absoluta
        jLabel4.setText("Ruta Abosulta: " + rutasele);
        //Tamaño en bytes
        long tamaño = archivoSelecc.length();
        long tamañofinal = tamaño / 1024;
        jLabel5.setText("Tamaño: " + tamañofinal + " KB");

    }//GEN-LAST:event_listacarpetasValueChanged

    private void listaarchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaarchivosValueChanged
        // TODO add your handling code here:
        String elementoseleccionado = (String) listaarchivos.getSelectedValue();
        //  System.out.println("Elemento: "+ elementoseleccionado);
        String rutasele = txturl.getText().trim() + "\\" + elementoseleccionado;
        // System.out.println("Ruta elemento Seleccionado: "+ rutasele);
        //Conseguir la fecha de ultima actualizacion
        File archivoSelecc = new File(rutasele);
        long modificacion = archivoSelecc.lastModified();
        Date modiDate = new Date(modificacion);
        SimpleDateFormat fechamodificacion = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = fechamodificacion.format(modiDate);
        jLabel3.setText("Fecha modificacion: " + fecha);
        jLabel4.setText("Ruta Abosulta: " + rutasele);

        //Tamaño en kb
        long tamaño = archivoSelecc.length();
        long tamañofinal = tamaño / 1024;
        jLabel5.setText("Tamaño: " + tamañofinal + " KB");
    }//GEN-LAST:event_listaarchivosValueChanged

    private void listaocultosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaocultosValueChanged
        // TODO add your handling code here:
        String elementoseleccionado = (String) listaocultos.getSelectedValue();
        // System.out.println("Elemento: "+ elementoseleccionado);
        String rutasele = txturl.getText().trim() + "\\" + elementoseleccionado;
        // System.out.println("Ruta elemento Seleccionado: "+ rutasele);

        //Conseguir la fecha de ultima actualizacion
        File archivoSelecc = new File(rutasele);
        long modificacion = archivoSelecc.lastModified();
        Date modiDate = new Date(modificacion);
        SimpleDateFormat fechamodificacion = new SimpleDateFormat("dd/MM/yyyy");
        String fecha = fechamodificacion.format(modiDate);
        jLabel3.setText("Fecha modificacion: " + fecha);
        jLabel4.setText("Ruta Abosulta: " + rutasele);
        //Tamaño del archivo
        long tamaño = archivoSelecc.length();
        long tamañofinal = tamaño / 1024;
        jLabel5.setText("Tamaño: " + tamañofinal + " KB");
    }//GEN-LAST:event_listaocultosValueChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaarchivos;
    private javax.swing.JList<String> listacarpetas;
    private javax.swing.JList<String> listaocultos;
    private javax.swing.JTextField txturl;
    // End of variables declaration//GEN-END:variables
}
